[tool.ruff]
target-version = "py314"
line-length = 79
exclude = [
    ".devcontainers",
    ".github",
    "migrations",
    "how-to-indent-in-python/sample_code.py"
]

[tool.ruff.lint]
select = ["E", "F", "RUF100"]
ignore = ["E501", "I"]

[tool.ruff.lint.isort]
force-sort-within-sections = true

