[tool.black]
line-length = 70
target-version = ["py312"]
exclude = '''
/(
  \.git
  | venv
  | migrations
  | node_modules
)/
'''


[tool.ruff]
target-version = "py312"
exclude        = [".git", "venv", "migrations", "node_modules"]
line-length = 70

[tool.ruff.lint]
select = ["E", "F", "I", "RUF100"]
ignore = ["E501"]                  # Line length is handled by Black